// Code generated by gencsources.go. DO NOT EDIT.

#include "csources/glfw/src/win32_init.c"
#include "csources/glfw/src/win32_module.c"
#include "csources/glfw/src/win32_joystick.c"
#include "csources/glfw/src/win32_monitor.c"
#include "csources/glfw/src/win32_time.c"
#include "csources/glfw/src/win32_thread.c"
#include "csources/glfw/src/win32_window.c"
#include "csources/glfw/src/wgl_context.c"
