// Code generated by gencsources.go. DO NOT EDIT.

#include "csources/glfw/src/x11_init.c"
#include "csources/glfw/src/x11_monitor.c"
#include "csources/glfw/src/x11_window.c"
#include "csources/glfw/src/xkb_unicode.c"
#include "csources/glfw/src/glx_context.c"
#include "csources/glfw/src/posix_time.c"
#include "csources/glfw/src/posix_thread.c"
#include "csources/glfw/src/posix_module.c"
#include "csources/glfw/src/posix_poll.c"
#include "csources/glfw/src/linux_joystick.c"
