// Code generated by gencsources.go. DO NOT EDIT.
//
// GLFW's internal.h requires this file. The platform backend is selected via
// cgo CFLAGS (-D_GLFW_COCOA / -D_GLFW_X11 / -D_GLFW_WIN32), so nothing is
// defined here.
